/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AImagePreviewGroup: typeof import('ant-design-vue/es')['ImagePreviewGroup']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Carousel: typeof import('./src/components/index/Carousel.vue')['default']
    Concept: typeof import('./src/components/index/Concept.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GoodCard: typeof import('./src/components/GoodCard.vue')['default']
    ImgGroup: typeof import('./src/components/ImgGroup.vue')['default']
    Info: typeof import('./src/components/index/Info.vue')['default']
    Menu: typeof import('./src/components/index/Menu.vue')['default']
    MoreBtn: typeof import('./src/components/MoreBtn.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    News: typeof import('./src/components/index/News.vue')['default']
    NewsModal: typeof import('./src/components/NewsModal.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Store: typeof import('./src/components/index/Store.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}
